POST http://localhost:8079/cargobooking
Content-Type: application/json

{
  "bookingAmount": 100,
  "originLocation": "CNHKG",
  "destLocation" : "USNYC",
  "destArrivalDeadline" : "2019-09-28"
}

### "bookingId": "58560D6E"
